version: '3'
services:
  test1:
    image: watcher-test-1
    labels:
      - "docker-compose-watcher.watch=1"
      - "docker-compose-watcher.dir=${PWD}"
  test2:
    image: watcher-test-2
    labels:
      - "docker-compose-watcher.watch=1"
      - "docker-compose-watcher.dir=${PWD}"
