version: '3'
services:
  test1:
    image: watcher-test-1
    labels:
      - "docker-compose-watcher.watch=1"
      - "docker-compose-watcher.file=/Users/heiner/go/src/virtualzone.de/docker-compose-watcher/res/c1/compose1.yaml"
  test2:
    build:
      context: /Users/heiner/go/src/virtualzone.de/docker-compose-watcher/res
    labels:
      - "docker-compose-watcher.watch=1"
      - "docker-compose-watcher.file=/Users/heiner/go/src/virtualzone.de/docker-compose-watcher/res/c1/compose1.yaml"
  test3:
    build: /Users/heiner/go/src/virtualzone.de/docker-compose-watcher/res
    labels:
      - "docker-compose-watcher.watch=1"
      - "docker-compose-watcher.file=/Users/heiner/go/src/virtualzone.de/docker-compose-watcher/res/c1/compose1.yaml"
